CREATE TABLE USERS(
id VARCHAR PRIMARY KEY,
login VARCHAR(50) UNIQUE NOT NULL,
CPF VARCHAR(11) UNIQUE NOT NULL);

CREATE TABLE Empresa(
id VARCHAR PRIMARY KEY,
nome VARCHAR(50) UNIQUE NOT NULL,
CNPJ VARCHAR(18) UNIQUE NOT NULL,
saldo DOUBLE NOT NULL);